package com.ek.hibernate.model.pojo;
// Generated 2017-6-12 23:17:22 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Bookinfo generated by hbm2java
 */
@SuppressWarnings({ "rawtypes", "serial" })
public class Bookinfo implements java.io.Serializable {

	private String isbn;
	private String bookname;
	private String author;
	private String printaddress;
	private Double price;
	private Double sellprice;
	private Integer printnumber;
	private Date printdate;
	private Integer inbooknumber;
	private Integer remainnumber;
	private Date inbookdate;
	private byte[] bookimage;
	private String bookdescrption;
	private String booktype;
	 
	private Set sellbooks = new HashSet(0);

	public Bookinfo() {
	}

	public Bookinfo(String isbn, String bookname, String author, String printaddress, Double price, int inbooknumber) {
		this.isbn = isbn;
		this.bookname = bookname;
		this.author = author;
		this.printaddress = printaddress;
		this.price = price;
		this.inbooknumber = inbooknumber;
	}

	public Bookinfo(String isbn, String bookname, String author, String printaddress, Double price, Double sellprice,
			Integer printnumber, Date printdate, Integer inbooknumber, Integer remainnumber, Date inbookdate,
			byte[] bookimage, String bookdescrption, String booktype, Set sellbooks) {
		this.isbn = isbn;
		this.bookname = bookname;
		this.author = author;
		this.printaddress = printaddress;
		this.price = price;
		this.sellprice = sellprice;
		this.printnumber = printnumber;
		this.printdate = printdate;
		this.inbooknumber = inbooknumber;
		this.remainnumber = remainnumber;
		this.inbookdate = inbookdate;
		this.bookimage = bookimage;
		this.bookdescrption = bookdescrption;
		this.booktype = booktype;
		this.sellbooks = sellbooks;
	}

	public String getIsbn() {
		return isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	public String getBookname() {
		return bookname;
	}

	public void setBookname(String bookname) {
		this.bookname = bookname;
	}

	public String getAuthor() {
		return author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getPrintaddress() {
		return printaddress;
	}

	public void setPrintaddress(String printaddress) {
		this.printaddress = printaddress;
	}

	public Double getPrice() {
		return price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public Double getSellprice() {
		return sellprice;
	}

	public void setSellprice(Double sellprice) {
		this.sellprice = sellprice;
	}

	public Integer getPrintnumber() {
		return printnumber;
	}

	public void setPrintnumber(Integer printnumber) {
		this.printnumber = printnumber;
	}

	public Date getPrintdate() {
		return printdate;
	}

	public void setPrintdate(Date printdate) {
		this.printdate = printdate;
	}

	public Integer getInbooknumber() {
		return inbooknumber;
	}

	public void setInbooknumber(Integer inbooknumber) {
		this.inbooknumber = inbooknumber;
	}

	public Integer getRemainnumber() {
		return remainnumber;
	}

	public void setRemainnumber(Integer remainnumber) {
		this.remainnumber = remainnumber;
	}

	public Date getInbookdate() {
		return inbookdate;
	}

	public void setInbookdate(Date inbookdate) {
		this.inbookdate = inbookdate;
	}

	public byte[] getBookimage() {
		return bookimage;
	}

	public void setBookimage(byte[] bookimage) {
		this.bookimage = bookimage;
	}

	public String getBookdescrption() {
		return bookdescrption;
	}

	public void setBookdescrption(String bookdescrption) {
		this.bookdescrption = bookdescrption;
	}

	public String getBooktype() {
		return booktype;
	}

	public void setBooktype(String booktype) {
		this.booktype = booktype;
	}

	public Set getSellbooks() {
		return sellbooks;
	}

	public void setSellbooks(Set sellbooks) {
		this.sellbooks = sellbooks;
	}
}
