package com.ek.hibernate.model.pojo;
// Generated 2017-6-12 23:17:22 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Userinfo generated by hbm2java
 */
@SuppressWarnings({ "rawtypes", "serial" })
public class Userinfo implements java.io.Serializable {
	 
	private String userid;
	private String username;
	private String userpassword;
	private String sex;
	private Integer age;
	private String postalcode;
	private String address;
	private String schoolage;
	private String personlike;
	private Date registerdate;
	private String usertype;

	private Set sellbooks = new HashSet(0);

	public Userinfo() {
	}

	public Userinfo(String userid, String username, String userpassword, String postalcode, String address) {
		this.userid = userid;
		this.username = username;
		this.userpassword = userpassword;
		this.postalcode = postalcode;
		this.address = address;
	}

	public Userinfo(String userid, String username, String userpassword, String sex, Integer age, String postalcode,
			String address, String schoolage, String personlike, Date registerdate, String usertype, Set sellbooks) {
		this.userid = userid;
		this.username = username;
		this.userpassword = userpassword;
		this.sex = sex;
		this.age = age;
		this.postalcode = postalcode;
		this.address = address;
		this.schoolage = schoolage;
		this.personlike = personlike;
		this.registerdate = registerdate;
		this.usertype = usertype;
		this.sellbooks = sellbooks;
	}

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getUserpassword() {
		return this.userpassword;
	}

	public void setUserpassword(String userpassword) {
		this.userpassword = userpassword;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public String getPostalcode() {
		return this.postalcode;
	}

	public void setPostalcode(String postalcode) {
		this.postalcode = postalcode;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getSchoolage() {
		return this.schoolage;
	}

	public void setSchoolage(String schoolage) {
		this.schoolage = schoolage;
	}

	public String getPersonlike() {
		return this.personlike;
	}

	public void setPersonlike(String personlike) {
		this.personlike = personlike;
	}

	public Date getRegisterdate() {
		return this.registerdate;
	}

	public void setRegisterdate(Date registerdate) {
		this.registerdate = registerdate;
	}

	public String getUsertype() {
		return this.usertype;
	}

	public void setUsertype(String usertype) {
		this.usertype = usertype;
	}

	public Set getSellbooks() {
		return this.sellbooks;
	}

	public void setSellbooks(Set sellbooks) {
		this.sellbooks = sellbooks;
	}

}
