package com.ek.hibernate.model.pojo3;
// Generated 2017-6-24 13:24:48 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * Employee generated by hbm2java
 * 用户类型有两种 一个 manager和common
 */
public class Employee implements java.io.Serializable {

	private Integer uuid;
	private String username;
	private String sex;
	private Date birthday;
//	private String emplyeeType;  // 这个就不能让允许用户操作了 要cut掉 配置文件里也要cut 通过两个<subclass来操作
// private String hasChild;  //这个是管理员关心的属性 放在EmployeeManager 中
//	private String isMarried;  //这个是普通员工关心的 放在EmployeeCommon 中

	public Employee() {
	}

	public Employee(String username, String sex, Date birthday) {
		this.username = username;
		this.sex = sex;
		this.birthday = birthday;
	}

	public Integer getUuid() {
		return this.uuid;
	}

	public void setUuid(Integer uuid) {
		this.uuid = uuid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}
}