package com.ek.hibernate.model.pojo2;
// Generated 2017-6-16 3:18:52 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * ZLesson generated by hbm2java
 */
public class ZLesson implements java.io.Serializable {

	private Integer uuid;
	private String leName;
	private Integer hours;
	private Set zTeachers = new HashSet(0);
	//private Set zStudentZLesson = new HashSet(0);  这个就不要了 多对多的情况 中间表的对象和映射文件 直接删掉 简化开发
	private Set  zStudent = new HashSet(0); //多对多就做成这样 映射文件改成 many-to-many

	public ZLesson() {
	}

	public ZLesson(String leName, Integer hours, Set zTeachers, Set zStudent) {
		this.leName = leName;
		this.hours = hours;
		this.zTeachers = zTeachers;
		this.zStudent = zStudent;
	}

	public Integer getUuid() {
		return this.uuid;
	}

	public void setUuid(Integer uuid) {
		this.uuid = uuid;
	}

	public String getLeName() {
		return this.leName;
	}

	public void setLeName(String leName) {
		this.leName = leName;
	}

	public Integer getHours() {
		return this.hours;
	}

	public void setHours(Integer hours) {
		this.hours = hours;
	}

	public Set getzTeachers() {
		return zTeachers;
	}

	public void setzTeachers(Set zTeachers) {
		this.zTeachers = zTeachers;
	}

	public Set getzStudent() {
		return zStudent;
	}

	public void setzStudent(Set zStudent) {
		this.zStudent = zStudent;
	}
}