package com.ek.hibernate.model.pojo2;
// Generated 2017-6-16 3:18:52 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * ZStudent generated by hbm2java
 */
public class ZStudent implements java.io.Serializable {

	private Integer uuid;
	private String stName;
	private String stSex;
	private ZAddress zAddress;
	//private Set zStudentZLesson = new HashSet(0);  这个就不要了 多对多的情况 中间表的对象和映射文件 直接删掉 简化开发
	private Set zLesson = new HashSet(0); //多对多就做成这样 映射文件改成 many-to-many
	
	public ZStudent() {
	}

	public ZStudent(ZAddress zAddress, String stName, String stSex, Set zLesson) {
		this.zAddress = zAddress;
		this.stName = stName;
		this.stSex = stSex;
		this.zLesson = zLesson;
	}

	public Integer getUuid() {
		return this.uuid;
	}

	public void setUuid(Integer uuid) {
		this.uuid = uuid;
	}

	public ZAddress getzAddress() {
		return zAddress;
	}

	public void setzAddress(ZAddress zAddress) {
		this.zAddress = zAddress;
	}

	public String getStName() {
		return this.stName;
	}

	public void setStName(String stName) {
		this.stName = stName;
	}

	public String getStSex() {
		return this.stSex;
	}

	public void setStSex(String stSex) {
		this.stSex = stSex;
	}

	public Set getzLesson() {
		return zLesson;
	}

	public void setzLesson(Set zLesson) {
		this.zLesson = zLesson;
	}
}